version: "3.8"

services:
  flask:
    build: ./
    container_name: flask
    ports:
      - "8080:8080"
    volumes:
      - .:/task-exercise
    environment:
      - FLASK_ENV=development
    command: flask run --host=0.0.0.0 --port=8080
